<section class="panel detail-panel mt-4"><h2>Consumíveis da OS</h2><div class="table-responsive"><table class="table app-table"><thead><tr><th>Material</th><th>Unidade</th><th>Reservado</th><th>Entregue</th><th>Consumido</th><th>Devolvido</th><th>Situação</th></tr></thead><tbody>
<?php foreach ($reservations as $reservation): ?><tr><td><?= esc($reservation['nome_con']) ?></td><td><?= esc($reservation['unidade_con']) ?></td><td><?= esc($reservation['quantidade_rco']) ?></td><td><?= esc($reservation['entregue_rco']) ?></td><td><?= esc($reservation['consumido_rco']) ?></td><td><?= esc($reservation['devolvido_rco']) ?></td><td><?= esc(['reservada' => 'Reservada no depósito', 'entregue' => 'Em custódia — conciliação pendente', 'conciliada' => 'Conciliada', 'liberada' => 'Liberada'][$reservation['status_rco']]) ?></td></tr><?php endforeach ?>
<?php if (!$reservations): ?><tr><td colspan="7">Nenhum consumível vinculado.</td></tr><?php endif ?>
</tbody></table></div>
<?php if ($can('os.consumiveis.reserve') && $orderRecord['status_oss'] === 'atribuida'): ?><h3>Reservar no depósito</h3><p>A reserva reduz a disponibilidade; o saldo físico permanece no depósito.</p><form data-confirm="Confirmar a reserva para esta OS?" method="post" action="<?= site_url('os/' . $orderRecord['id_oss'] . '/consumiveis/reservar') ?>" data-validate><?= csrf_field() ?><input type="hidden" name="_confirmacao" value="pendente"><div class="row g-3">
<?= app_field('consumivel', 'Material', $input, $errors, ['required' => true, 'choices' => ['' => 'Selecione'] + array_combine(array_column($materials, 'id_con'), array_map(static fn ($m) => $m['nome_con'] . ' (' . $m['unidade_con'] . ', ' . $m['precisao_con'] . ' casas decimais)', $materials))]) ?>
<?= app_field('quantidade', 'Quantidade a reservar', $input, $errors, ['required' => true, 'max' => 16]) ?>
</div><button class="btn btn-primary mt-3" type="submit">Reservar material</button></form><?php endif ?>
</section>

<?php foreach ($reservations as $reservation): ?>
<?php if ($can('os.consumiveis.deliver') && $orderRecord['status_oss'] === 'atribuida' && $reservation['status_rco'] === 'reservada'): ?>
<section class="panel form-panel mt-4"><h3>Entregar <?= esc($reservation['nome_con']) ?></h3><p>Confirme a entrega física de <?= esc($reservation['quantidade_rco']) ?> <?= esc($reservation['unidade_con']) ?> ao Eletricista responsável.</p><form method="post" action="<?= site_url('os/' . $orderRecord['id_oss'] . '/consumiveis/' . $reservation['id_rco'] . '/entregar') ?>" data-confirm="Confirmar a entrega física integral desta reserva?"><?= csrf_field() ?><input type="hidden" name="_confirmacao" value="pendente"><button class="btn btn-primary" type="submit">Confirmar entrega física</button></form></section>
<?php endif ?>
<?php if ($can('os.consumiveis.receive') && $reservation['status_rco'] === 'entregue'): ?>
<?php $returnInput = ($input['reserva_devolucao'] ?? null) === (int) $reservation['id_rco'] ? $input : []; $prefix = 'devolucao-' . $reservation['id_rco']; ?>
<section class="panel form-panel mt-4"><h3>Receber devolução de <?= esc($reservation['nome_con']) ?></h3><form data-confirm="Confirmar o recebimento físico deste material?" method="post" action="<?= site_url('os/' . $orderRecord['id_oss'] . '/consumiveis/' . $reservation['id_rco'] . '/receber') ?>" data-validate><?= csrf_field() ?><input type="hidden" name="_confirmacao" value="pendente"><div class="row g-3"><div class="col-md-6"><label class="form-label" for="<?= esc($prefix) ?>-quantidade">Quantidade recebida *</label><input class="form-control <?= isset($errors['quantidade_devolucao']) ? 'is-invalid' : '' ?>" id="<?= esc($prefix) ?>-quantidade" name="quantidade_devolucao" value="<?= esc($returnInput['quantidade_devolucao'] ?? '') ?>" maxlength="16" inputmode="decimal" required <?= isset($errors['quantidade_devolucao']) ? 'aria-invalid="true" aria-describedby="' . esc($prefix) . '-quantidade-error"' : '' ?>><?php if (isset($errors['quantidade_devolucao'])): ?><div class="invalid-feedback" id="<?= esc($prefix) ?>-quantidade-error"><?= esc($errors['quantidade_devolucao']) ?></div><?php endif ?></div>
<div class="col-md-6"><label class="form-label" for="<?= esc($prefix) ?>-observacao">Referência ou motivo *</label><input class="form-control <?= isset($errors['observacao_devolucao']) ? 'is-invalid' : '' ?>" id="<?= esc($prefix) ?>-observacao" name="observacao_devolucao" value="<?= esc($returnInput['observacao_devolucao'] ?? '') ?>" maxlength="255" required <?= isset($errors['observacao_devolucao']) ? 'aria-invalid="true" aria-describedby="' . esc($prefix) . '-observacao-error"' : '' ?>><?php if (isset($errors['observacao_devolucao'])): ?><div class="invalid-feedback" id="<?= esc($prefix) ?>-observacao-error"><?= esc($errors['observacao_devolucao']) ?></div><?php endif ?></div></div><button class="btn btn-primary mt-3" type="submit">Registrar recebimento físico</button></form></section>
<?php endif ?>
<?php endforeach ?>

<?php if ($can('os.consumiveis.consume') && $orderRecord['status_oss'] === 'em_atendimento'): ?>
<?php foreach ($reservations as $reservation): ?>
<?php if ($reservation['status_rco'] === 'entregue'): ?>
<?php $consumeInput = ($input['reserva_consumo'] ?? null) === (int) $reservation['id_rco'] ? $input : []; $consumeErrors = ($input['reserva_consumo'] ?? null) === (int) $reservation['id_rco'] ? $errors : []; $prefix = 'consumo-' . $reservation['id_rco']; ?>
<section class="panel form-panel mt-4"><h3>Registrar consumo de <?= esc($reservation['nome_con']) ?></h3><p>Informe o material usado neste atendimento, em <?= esc($reservation['unidade_con']) ?>.</p><form data-confirm="Confirmar o consumo deste material na OS?" method="post" action="<?= site_url('os/'.$orderRecord['id_oss'].'/consumiveis/'.$reservation['id_rco'].'/consumir') ?>" data-validate><?= csrf_field() ?><input type="hidden" name="_confirmacao" value="pendente"><div class="row g-3">
<?php foreach (['quantidade_consumo'=>'Quantidade consumida','observacao_consumo'=>'Referência ou motivo'] as $field=>$label): ?>
<?php $error = $consumeErrors[$field] ?? null; $fieldId = $prefix . '-' . $field; ?>
<div class="col-md-6"><label for="<?= esc($fieldId) ?>" class="form-label"><?= esc($label) ?> *</label><input id="<?= esc($fieldId) ?>" class="form-control <?= $error ? 'is-invalid' : '' ?>" name="<?= esc($field) ?>" value="<?= esc($consumeInput[$field] ?? '') ?>" required maxlength="<?= $field === 'quantidade_consumo' ? '16' : '255' ?>" <?= $field === 'quantidade_consumo' ? 'inputmode="decimal"' : '' ?> <?= $error ? 'aria-invalid="true" aria-describedby="' . esc($fieldId) . '-error"' : '' ?>><?php if ($error): ?><div class="invalid-feedback" id="<?= esc($fieldId) ?>-error"><?= esc($error) ?></div><?php endif ?></div>
<?php endforeach ?>
</div><button type="submit" class="btn btn-primary mt-3">Registrar consumo</button></form></section>
<?php endif ?>
<?php endforeach ?>
<?php endif ?>
